# Generated by Django 5.1.7 on 2025-04-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('duracion', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tratamientos/')),
            ],
        ),
    ]
