# Generated by Django 5.1.7 on 2025-04-02 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.tratamiento')),
            ],
        ),
    ]
