# Generated by Django 5.1.7 on 2025-04-03 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_alter_horarioatencion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='intervalo_minutos',
            field=models.PositiveIntegerField(default=60, help_text='Duración en minutos del tratamiento. Esto determina cuánto bloquea en el horario.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
