# Generated by Django 5.1.7 on 2025-04-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_alter_tratamiento_intervalo_minutos'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Bloqueo de horario',
                'verbose_name_plural': 'Bloqueos de horario',
            },
        ),
    ]
