# Generated by Django 5.1.7 on 2025-04-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_bloqueohorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='event_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
