# Generated by Django 5.1.7 on 2025-04-06 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_cita_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='event_id',
            new_name='calendar_event_id',
        ),
    ]
