# Generated by Django 5.1.7 on 2025-04-16 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_rename_event_id_cita_calendar_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidades', models.ManyToManyField(related_name='especialistas', to='citas.tratamiento')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='especialista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.especialista'),
        ),
    ]
