# Generated by Django 5.1.7 on 2025-04-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0011_remove_tratamiento_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='descripcion_secundaria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
